name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Which version of ss3diags are you seeing the problem on?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: sessionInfo
    attributes:
      label: R Session Information
      description: Please provide information about R Session (R version, OS, Dependencies including r4ss and SS3 versions).
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here. 
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        By submitting this issue, you agree to follow our 
        [Code of Conduct](https://github.com/nmfs-ost/ss3diags/blob/main/CODE_OF_CONDUCT.md).
      
        ---

        Before filling out this report please search the existing issues to see
        if the problem has already been reported. If it has, please add a
        comment to the open issue or link to the related, but closed, issue in
        this report.
